### PR TITLE
Updated to 1.8

### PR DESCRIPTION
**Pull request by anmol26s**

### CODE REVIEW

**Comment by anaqreon** [comment]
I won't have a chance to test this update in the near future. Did you test it somehow (ideally on a fresh YunoHost test server)?

**Comment by anmol26s** [comment]
Have you checked the "/" in the nginx.conf file after location /  {..code..}. I did a reinstall month and half back, the package was working good at that time.The update is working fine though. I did not get time to check on a fresh install. But this weekend I will try it on a VM. The package need to update to 2.4 version too. https://forum.yunohost.org/t/news-about-app-management-and-packaging-in-yunohost-2-4/1379

**Comment by anaqreon** [comment]
Thanks for taking the lead on this. Since I don't actually host my hub using YunoHost, it's more difficult for me to test these things. I'll wait to merge until you've sorted this out.

**Comment by anmol26s** [comment]
I have installed test version of YunoHost from [https://github.com/YunoHost/ynh-dev](https://github.com/YunoHost/ynh-dev) and installed Hubzilla on it. The installation was successful with a warning.
**Warning: 'yunohost app initdb' is deprecated and will be removed in the future** 
The Hubzilla is running normal with no errors. 
Now only a restore, backup script needed with update  of the manifest 

Helpful links
https://yunohost.org/#/packaging_apps_manifest_en
https://github.com/YunoHost/example_ynh/tree/master/scripts

Thanks

**Comment by anmol26s** [comment]
@maclag 
Can you show me your nginx configuration for Hubzilla. I have not tested Hubzilla from quite some time.

**Comment by maclag** [comment]
@anmol26s 

Here it is, (replaced my domain name by mydomain.tld):

/etc/nginx/conf.d/hub.mydomain.tld.conf:

```
server {
    listen 80;
    listen [::]:80;
    server_name hub.mydomain.tld;

    access_by_lua_file /usr/share/ssowat/access.lua;

    include conf.d/hub.mydomain.tld.d/*.conf;

    location /yunohost/admin {
        return 301 https://$http_host$request_uri;
    }

    access_log /var/log/nginx/hub.mydomain.tld-access.log;
    error_log /var/log/nginx/hub.mydomain.tld-error.log;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name hub.mydomain.tld;

    ssl_certificate /etc/yunohost/certs/hub.mydomain.tld/crt.pem;
    ssl_certificate_key /etc/yunohost/certs/hub.mydomain.tld/key.pem;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:50m;
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ALL:!aNULL:!eNULL:!LOW:!EXP:!RC4:!3DES:+HIGH:+MEDIUM;

    add_header Strict-Transport-Security "max-age=31536000;";

    # Uncomment the following directive after DH generation
    # > openssl dhparam -out /etc/ssl/private/dh2048.pem -outform PEM -2 2048
    #ssl_dhparam /etc/ssl/private/dh2048.pem;

    access_by_lua_file /usr/share/ssowat/access.lua;

    include conf.d/hub.mydomain.tld.d/*.conf;

    include conf.d/yunohost_admin.conf.inc;
    include conf.d/yunohost_api.conf.inc;

    access_log /var/log/nginx/hub.mydomain.tld-access.log;
    error_log /var/log/nginx/hub.mydomain.tld-error.log;
}

```

/etc/nginx/conf.d/hub.mydomain.tld.d/hubzilla.conf

```
location /  {

  # Path to source
  alias /var/www/hubzilla// ;

  # Force https
  if ($scheme = http) {
    rewrite ^ https://$server_name$request_uri? permanent;
  }

  # Example PHP configuration
  index index.php index.html;
  try_files $uri $uri/ index.php;
  location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param   REMOTE_USER   $remote_user;
    fastcgi_param  PATH_INFO $fastcgi_path_info;
    fastcgi_param SCRIPT_FILENAME $request_filename;
  }
  
  # .htaccess file from Hubzilla converted using http://winginx.com/en/htaccess
  location ~ "(^|/)\.git" { return 403; } 
  location ~ "(^|/)store" { return 403; } 
  autoindex off; 
  location / { if (!-e $request_filename){ rewrite ^(.*)$ /index.php?q=$1; } } 
  location ~ \.(out|log|gz)$ { deny all; }

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
}
```

**Comment by anmol26s** [comment]
looks good
can you give detail of exact error please

**Comment by maclag** [comment]
In /var/log/nginx/hub.mydomain.tld-error.log:

`2016/12/31 10:35:02 [error] 31231#0: *11675 FastCGI sent in stderr: "PHP message: PHP Fatal 
error:  Cannot redeclare identity_check_service_class() (previously declared in /var/www/hubzilla/include/identity.php:24) in /var/www/hubzilla/include/channel.php on line 24" while reading response header from upstream, client: xx.xx.xx.xx, server: hub.mydomain.tld, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "hub.mydomain.tld", referrer: "https://mydomain.tld/yunohost/sso/"`

**Comment by anmol26s** [comment]
can you remove /var/www/hubzilla/include/identify.php and check if it works?

**Comment by maclag** [comment]
Well, I suppose that was to be expected:

```
2016/12/31 12:08:38 [error] 26796#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(include/identity.php): failed to open stream: No such file or directory in /var/www/hubzilla/boot.php on line 43
PHP message: PHP Fatal error:  require_once(): Failed opening required 'include/identity.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/hubzilla/boot.php on line 43" while reading response header from upstream, client: xx.xx.xx.xx, server: hub.mydomain.tld, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "hub.mydomain.tld", referrer: "https://mydomain.tld/yunohost/sso/"
```
I tried to comment out the require_once line in boot.php, but now I have:

`2016/12/31 12:14:39 [error] 27304#0: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare channelx_by_nick() (previously declared in /var/www/hubzilla/include/Contact.php:51) in /var/www/hubzilla/include/channel.php on line 1806" while reading response header from upstream, client: xx.xx.xx.xx, server: hub.mydomain.tld, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "hub.mydomain.tld", referrer: "https://mydomain.tld/yunohost/sso/"
`

**Comment by anmol26s** [comment]
i do not see the contact.php in the original huzilla package: https://github.com/redmatrix/hubzilla/tree/master/include
i think the package need to be updated with the latest release. you can pull from the  from orignal hubzilla so that you have the updated files.

**Pull request merged**
