### PR TITLE
Updated to 1.4

### PR DESCRIPTION
**Pull request by anmol26s**

### CODE REVIEW

**Comment by anaqreon** [comment]
I cloned Hubzilla core, checked out tag 1.4, then cloned Hubzilla official addons and checkout out tag 1.4. When I run a diff on the sources folder from your pull request commit (275b30a) I get the following:
```

$ diff -rq --exclude=.git* zot/hubzilla-yunohost/sources/ hubzilla-temp/
Only in zot/hubzilla-yunohost/sources/doc/hook: discover_by_webbie.bb
Only in zot/hubzilla-yunohost/sources/: extend
Only in zot/hubzilla-yunohost/sources/include: AccessList.php
Only in zot/hubzilla-yunohost/sources/include: DReport.php
Only in zot/hubzilla-yunohost/sources/include: RedDAV
Only in zot/hubzilla-yunohost/sources/include: salmon.php
Only in zot/hubzilla-yunohost/sources/include: session.php
Only in zot/hubzilla-yunohost/sources/view/css: mod_register.css
Only in zot/hubzilla-yunohost/sources/view/pdl: mod_new_channel.pdl
Only in zot/hubzilla-yunohost/sources/view/pdl: mod_register.pdl
Files zot/hubzilla-yunohost/sources/view/theme/redbasic/schema/bluegrid.css and hubzilla-temp/view/theme/redbasic/schema/bluegrid.css differ
Only in zot/hubzilla-yunohost/sources/view/tpl: magicsig.tpl
Only in zot/hubzilla-yunohost/sources/view/tpl: profile_hide_friends.tpl
```

Are these differences intentional? Are they necessary somehow for the YunoHost app to install and work properly?

**Comment by anmol26s** [comment]
I only merged the the new release 1.4 to the sources folder and addons to addon.
I don't know why these are different. Have you cloned from development or the release 1.4?
Is there any line to line comparing tool which can compare them?

**Comment by anaqreon** [comment]
I feel like we should be able to use submodules to make this easier.

**Comment by anmol26s** [comment]
How don't know about submodules.
After the update 1.4. I can not get updates from the dispora. And dispora connector is disabled in the pulgins. Its says non compatible with current version. Is it now working in the current version?

**Pull request closed without merging**
